// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpsL4h2LPVGqDo6FxrHE18gS9hvYeGFYE',
    appId: '1:1041069115258:web:5716ad3c7cb5beb0d6b8c3',
    messagingSenderId: '1041069115258',
    projectId: 'libhub-project-oua',
    authDomain: 'libhub-project-oua.firebaseapp.com',
    storageBucket: 'libhub-project-oua.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBpXn0_KXKnXCwceDwXk-4sWcFKwySNhU',
    appId: '1:1041069115258:android:0cc0fe67ca9f2c22d6b8c3',
    messagingSenderId: '1041069115258',
    projectId: 'libhub-project-oua',
    storageBucket: 'libhub-project-oua.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCkP2vuLzSCJzcpgvVeWJjaeECI1jBQwI',
    appId: '1:1041069115258:ios:d4d2effea8f45817d6b8c3',
    messagingSenderId: '1041069115258',
    projectId: 'libhub-project-oua',
    storageBucket: 'libhub-project-oua.appspot.com',
    iosBundleId: 'com.example.libhub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCkP2vuLzSCJzcpgvVeWJjaeECI1jBQwI',
    appId: '1:1041069115258:ios:d4d2effea8f45817d6b8c3',
    messagingSenderId: '1041069115258',
    projectId: 'libhub-project-oua',
    storageBucket: 'libhub-project-oua.appspot.com',
    iosBundleId: 'com.example.libhub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpsL4h2LPVGqDo6FxrHE18gS9hvYeGFYE',
    appId: '1:1041069115258:web:5375b6bde36692add6b8c3',
    messagingSenderId: '1041069115258',
    projectId: 'libhub-project-oua',
    authDomain: 'libhub-project-oua.firebaseapp.com',
    storageBucket: 'libhub-project-oua.appspot.com',
  );
}
